#!/usr/bin/env sh

staged_files="$(git diff --cached --name-only --diff-filter=ACMR | grep -E '\.(js|jsx|ts|tsx|json|jsonc|css|scss|html|md)$' || true)"

if [ -z "$staged_files" ]; then
	exit 0
fi

echo "$staged_files" | xargs bunx biome format --write
echo "$staged_files" | xargs git add
